const data = [
    {
        id: "1",
        name: "Refined Steel Shoes",
        image: "https://picsum.photos/640/480/",
        price: "849.00",
        status: false,
        quantity: 82644,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "2",
        name: "Tasty Concrete Chips",
        image: "https://picsum.photos/640/480/",
        price: "762.00",
        status: true,
        quantity: 57587,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "3",
        name: "Awesome Soft Fish",
        image: "https://picsum.photos/640/480/",
        price: "633.00",
        status: false,
        quantity: 51117,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "4",
        name: "Gorgeous Concrete Car",
        image: "https://picsum.photos/640/480/",
        price: "728.00",
        status: false,
        quantity: 56,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "5",
        name: "Fantastic Fresh Fish",
        image: "https://picsum.photos/640/480/",
        price: "364.00",
        status: true,
        quantity: 7373,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "6",
        name: "Gorgeous Metal Soap",
        image: "https://picsum.photos/640/480/",
        price: "654.00",
        status: true,
        quantity: 26,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "7",
        name: "Tasty Fresh Pizza",
        image: "https://picsum.photos/640/480/",
        price: "795.00",
        status: true,
        quantity: 61,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "8",
        name: "Tasty Concrete Towels",
        image: "https://picsum.photos/640/480/",
        price: "513.00",
        status: false,
        quantity: 36,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "9",
        name: "Awesome Metal Computer",
        image: "https://picsum.photos/640/480/",
        price: "741.00",
        status: false,
        quantity: 29,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
    {
        id: "10",
        name: "Small Rubber Cheese",
        image: "https://picsum.photos/640/480/",
        price: "471.00",
        status: true,
        quantity: 42,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia molestias facere saepe eaque fugit.",
    },
];
export default data;